<?php

namespace Shopware\Proxies\__CG__\Shopware\Models\Article;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Detail extends \Shopware\Models\Article\Detail implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'id', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'articleId', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'unitId', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'number', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'supplierNumber', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'kind', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'additionalText', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'active', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'inStock', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'stockMin', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'weight', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'width', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'len', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'height', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'ean', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'purchasePrice', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'position', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'minPurchase', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'purchaseSteps', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'maxPurchase', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'purchaseUnit', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'referenceUnit', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'packUnit', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'shippingFree', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'releaseDate', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'shippingTime', 'article', 'prices', 'attribute', 'unit', 'configuratorOptions', 'esd', 'notifications', 'images'];
        }

        return ['__isInitialized__', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'id', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'articleId', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'unitId', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'number', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'supplierNumber', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'kind', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'additionalText', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'active', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'inStock', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'stockMin', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'weight', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'width', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'len', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'height', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'ean', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'purchasePrice', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'position', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'minPurchase', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'purchaseSteps', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'maxPurchase', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'purchaseUnit', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'referenceUnit', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'packUnit', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'shippingFree', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'releaseDate', '' . "\0" . 'Shopware\\Models\\Article\\Detail' . "\0" . 'shippingTime', 'article', 'prices', 'attribute', 'unit', 'configuratorOptions', 'esd', 'notifications', 'images'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Detail $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', [$number]);

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', []);

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupplierNumber($supplierNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupplierNumber', [$supplierNumber]);

        return parent::setSupplierNumber($supplierNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplierNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplierNumber', []);

        return parent::getSupplierNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setKind($kind)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKind', [$kind]);

        return parent::setKind($kind);
    }

    /**
     * {@inheritDoc}
     */
    public function getKind()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKind', []);

        return parent::getKind();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdditionalText($additionalText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdditionalText', [$additionalText]);

        return parent::setAdditionalText($additionalText);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdditionalText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdditionalText', []);

        return parent::getAdditionalText();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setInStock($inStock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInStock', [$inStock]);

        return parent::setInStock($inStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getInStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInStock', []);

        return parent::getInStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setStockMin($stockMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStockMin', [$stockMin]);

        return parent::setStockMin($stockMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockMin', []);

        return parent::getStockMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeight($weight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeight', [$weight]);

        return parent::setWeight($weight);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeight', []);

        return parent::getWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', [$position]);

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', []);

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function getArticleId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticleId', []);

        return parent::getArticleId();
    }

    /**
     * {@inheritDoc}
     */
    public function getArticle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticle', []);

        return parent::getArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticle(\Shopware\Models\Article\Article $article)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticle', [$article]);

        return parent::setArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', []);

        return parent::getAttribute();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($attribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', [$attribute]);

        return parent::setAttribute($attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrices', []);

        return parent::getPrices();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrices($prices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrices', [$prices]);

        return parent::setPrices($prices);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidth', []);

        return parent::getWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidth($width)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidth', [$width]);

        return parent::setWidth($width);
    }

    /**
     * {@inheritDoc}
     */
    public function getLen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLen', []);

        return parent::getLen();
    }

    /**
     * {@inheritDoc}
     */
    public function setLen($length)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLen', [$length]);

        return parent::setLen($length);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeight', []);

        return parent::getHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeight($height)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeight', [$height]);

        return parent::setHeight($height);
    }

    /**
     * {@inheritDoc}
     */
    public function getEan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEan', []);

        return parent::getEan();
    }

    /**
     * {@inheritDoc}
     */
    public function setEan($ean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEan', [$ean]);

        return parent::setEan($ean);
    }

    /**
     * {@inheritDoc}
     */
    public function setPurchasePrice($purchasePrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurchasePrice', [$purchasePrice]);

        return parent::setPurchasePrice($purchasePrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchasePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchasePrice', []);

        return parent::getPurchasePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingTime($shippingTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingTime', [$shippingTime]);

        return parent::setShippingTime($shippingTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingTime', []);

        return parent::getShippingTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingFree($shippingFree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingFree', [$shippingFree]);

        return parent::setShippingFree($shippingFree);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingFree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingFree', []);

        return parent::getShippingFree();
    }

    /**
     * {@inheritDoc}
     */
    public function setReleaseDate($releaseDate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReleaseDate', [$releaseDate]);

        return parent::setReleaseDate($releaseDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getReleaseDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReleaseDate', []);

        return parent::getReleaseDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinPurchase($minPurchase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinPurchase', [$minPurchase]);

        return parent::setMinPurchase($minPurchase);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinPurchase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinPurchase', []);

        return parent::getMinPurchase();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurchaseSteps($purchaseSteps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurchaseSteps', [$purchaseSteps]);

        return parent::setPurchaseSteps($purchaseSteps);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchaseSteps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchaseSteps', []);

        return parent::getPurchaseSteps();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxPurchase($maxPurchase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxPurchase', [$maxPurchase]);

        return parent::setMaxPurchase($maxPurchase);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxPurchase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxPurchase', []);

        return parent::getMaxPurchase();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurchaseUnit($purchaseUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurchaseUnit', [$purchaseUnit]);

        return parent::setPurchaseUnit($purchaseUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchaseUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchaseUnit', []);

        return parent::getPurchaseUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferenceUnit($referenceUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferenceUnit', [$referenceUnit]);

        return parent::setReferenceUnit($referenceUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferenceUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferenceUnit', []);

        return parent::getReferenceUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPackUnit($packUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackUnit', [$packUnit]);

        return parent::setPackUnit($packUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackUnit', []);

        return parent::getPackUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function getUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnit', []);

        return parent::getUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnit($unit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnit', [$unit]);

        return parent::setUnit($unit);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfiguratorOptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfiguratorOptions', []);

        return parent::getConfiguratorOptions();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfiguratorOptions($configuratorOptions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfiguratorOptions', [$configuratorOptions]);

        return parent::setConfiguratorOptions($configuratorOptions);
    }

    /**
     * {@inheritDoc}
     */
    public function setEsd($esd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsd', [$esd]);

        return parent::setEsd($esd);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsd', []);

        return parent::getEsd();
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setImages($images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImages', [$images]);

        return parent::setImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function fromArray(array $array = array (
), array $fillable = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromArray', [$array, $fillable]);

        return parent::fromArray($array, $fillable);
    }

    /**
     * {@inheritDoc}
     */
    public function setOneToOne($data, $model, $property, $reference = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOneToOne', [$data, $model, $property, $reference]);

        return parent::setOneToOne($data, $model, $property, $reference);
    }

    /**
     * {@inheritDoc}
     */
    public function setOneToMany($data, $model, $property, $reference = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOneToMany', [$data, $model, $property, $reference]);

        return parent::setOneToMany($data, $model, $property, $reference);
    }

    /**
     * {@inheritDoc}
     */
    public function setManyToOne($data, $model, $property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManyToOne', [$data, $model, $property]);

        return parent::setManyToOne($data, $model, $property);
    }

}
