<?php

namespace Shopware\Proxies\__CG__\Shopware\Models\Customer;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Group extends \Shopware\Models\Customer\Group implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'id', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'key', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'name', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'tax', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'taxInput', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'mode', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'discount', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'minimumOrder', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'minimumOrderSurcharge', 'discounts', 'attribute', 'customers'];
        }

        return ['__isInitialized__', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'id', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'key', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'name', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'tax', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'taxInput', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'mode', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'discount', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'minimumOrder', '' . "\0" . 'Shopware\\Models\\Customer\\Group' . "\0" . 'minimumOrderSurcharge', 'discounts', 'attribute', 'customers'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Group $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setKey($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKey', [$key]);

        return parent::setKey($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKey', []);

        return parent::getKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTax($tax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTax', [$tax]);

        return parent::setTax($tax);
    }

    /**
     * {@inheritDoc}
     */
    public function getTax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTax', []);

        return parent::getTax();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxInput($taxInput)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxInput', [$taxInput]);

        return parent::setTaxInput($taxInput);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxInput()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxInput', []);

        return parent::getTaxInput();
    }

    /**
     * {@inheritDoc}
     */
    public function setMode($mode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMode', [$mode]);

        return parent::setMode($mode);
    }

    /**
     * {@inheritDoc}
     */
    public function getMode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMode', []);

        return parent::getMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount($discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', [$discount]);

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', []);

        return parent::getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinimumOrder($minimumOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinimumOrder', [$minimumOrder]);

        return parent::setMinimumOrder($minimumOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinimumOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinimumOrder', []);

        return parent::getMinimumOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinimumOrderSurcharge($minimumOrderSurcharge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinimumOrderSurcharge', [$minimumOrderSurcharge]);

        return parent::setMinimumOrderSurcharge($minimumOrderSurcharge);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinimumOrderSurcharge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinimumOrderSurcharge', []);

        return parent::getMinimumOrderSurcharge();
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscounts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscounts', []);

        return parent::getDiscounts();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscounts($discounts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscounts', [$discounts]);

        return parent::setDiscounts($discounts);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', []);

        return parent::getAttribute();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($attribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', [$attribute]);

        return parent::setAttribute($attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function fromArray(array $array = array (
), array $fillable = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromArray', [$array, $fillable]);

        return parent::fromArray($array, $fillable);
    }

    /**
     * {@inheritDoc}
     */
    public function setOneToOne($data, $model, $property, $reference = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOneToOne', [$data, $model, $property, $reference]);

        return parent::setOneToOne($data, $model, $property, $reference);
    }

    /**
     * {@inheritDoc}
     */
    public function setOneToMany($data, $model, $property, $reference = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOneToMany', [$data, $model, $property, $reference]);

        return parent::setOneToMany($data, $model, $property, $reference);
    }

    /**
     * {@inheritDoc}
     */
    public function setManyToOne($data, $model, $property)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManyToOne', [$data, $model, $property]);

        return parent::setManyToOne($data, $model, $property);
    }

}
